@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODNjMzFlYzAwY2ZjNmZlOTdhZWYzNSIsImZpcnN0TmFtZSI6ImpvaG4iLCJsYXN0TmFtZSI6IkRvZSIsImVtYWlsIjoiMjAwMmFua2l0MjAwMkBnbWFpbC5jb20iLCJudW1iZXIiOiIxMjM0NTY3ODkwIiwiYmlvIjpudWxsLCJpYXQiOjE3MTk5MTk0MzQsImV4cCI6MTcxOTkyMzAzNH0.Tox_-8fnzXGGH4RH0Lgqi8v-6db7GAsz6K8ezHKftbU


### Create Account API
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "firstName": "ankit",
  "lastName": "Doe",
  "email": "ankitkaushik.me2@gmail.com",
  "number": "1234567890"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "firstName": "ankit",
  "userPassword": "aDan90"
}



###
PATCH http://localhost:3000/user/update/bio
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bio": "hey there "
}
